import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Calendar, Clock, User } from "lucide-react";
import { Container } from "@/components/shared/Container";
import { ScrollReveal } from "@/components/shared/ScrollReveal";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

interface BlogPostPageProps {
  params: Promise<{ slug: string }>;
}

const posts: Record<
  string,
  {
    title: string;
    excerpt: string;
    category: string;
    date: string;
    readTime: string;
    author: string;
    gradient: string;
    content: React.ReactNode;
  }
> = {
  "future-of-ai-travel": {
    title: "The Future of AI Travel Planning",
    excerpt: "How large language models are reshaping the way we research, plan, and experience trips.",
    category: "AI",
    date: "Jan 12, 2026",
    readTime: "6 min read",
    author: "Alex Rivera",
    gradient: "from-sky-400 to-teal-400",
    content: (
      <>
        <p className="text-lg leading-relaxed mb-6">
          Artificial intelligence is no longer a futuristic concept for travel — it is the engine
          behind smarter, more personalized trips. At Talery, we are reimagining what it means to plan
          a journey from the first spark of inspiration to the final boarding pass.
        </p>
        <h2 className="text-2xl font-bold mt-10 mb-4">From Search to Conversation</h2>
        <p className="leading-relaxed mb-6">
          Traditional travel search is transactional. You input dates, destinations, and budgets, then
          sift through endless tabs. AI shifts the experience toward conversation. Travelers can
          describe a vibe — &ldquo;a quiet coastal town with great seafood and vintage bookshops&rdquo; — and
          receive tailored recommendations in seconds.
        </p>
        <h2 className="text-2xl font-bold mt-10 mb-4">Dynamic Itineraries</h2>
        <p className="leading-relaxed mb-6">
          Static itineraries are a thing of the past. Talery builds living plans that adapt to weather,
          local events, opening hours, and real-time traveler feedback. If a museum closes early or a
          hidden pop-up market appears, your itinerary evolves automatically.
        </p>
        <h2 className="text-2xl font-bold mt-10 mb-4">The Human Layer</h2>
        <p className="leading-relaxed">
          AI is powerful, but travel is deeply human. That is why Talery pairs intelligent suggestions
          with community stories, creator guides, and local tips. The result is a plan that feels
          curated by a well-traveled friend, not generated by a machine.
        </p>
      </>
    ),
  },
  "hidden-gems-europe": {
    title: "10 Hidden Gems in Europe for 2026",
    excerpt: "Skip the crowds and discover underrated villages, coastlines, and mountain towns across Europe.",
    category: "Destinations",
    date: "Jan 8, 2026",
    readTime: "8 min read",
    author: "Sofia Andersson",
    gradient: "from-teal-400 to-orange-400",
    content: (
      <>
        <p className="text-lg leading-relaxed mb-6">
          Europe is full of famous landmarks, but its real magic often hides in quiet villages,
          coastal trails, and mountain valleys. Here are ten underrated destinations worth adding to
          your 2026 travel list.
        </p>
        <h2 className="text-2xl font-bold mt-10 mb-4">1. Kotor Bay, Montenegro</h2>
        <p className="leading-relaxed mb-6">
          A fjord-like bay framed by medieval towns and steep hiking trails. Arrive early to beat the
          cruise crowds and hike the city walls at sunrise.
        </p>
        <h2 className="text-2xl font-bold mt-10 mb-4">2. The Azores, Portugal</h2>
        <p className="leading-relaxed mb-6">
          Volcanic islands in the middle of the Atlantic offer hot springs, crater lakes, and some of
          the best whale watching in Europe.
        </p>
        <h2 className="text-2xl font-bold mt-10 mb-4">3. Matera, Italy</h2>
        <p className="leading-relaxed">
          Ancient cave dwellings transformed into boutique hotels and restaurants. Matera feels like
          stepping into another era without the tourist crush of Rome or Florence.
        </p>
      </>
    ),
  },
  "creator-economy-travel": {
    title: "How Creators Are Building Travel Businesses",
    excerpt: "From sponsored trips to premium guides, creators are turning wanderlust into sustainable income.",
    category: "Creators",
    date: "Dec 28, 2025",
    readTime: "5 min read",
    author: "Marcus Chen",
    gradient: "from-orange-400 to-sky-400",
    content: (
      <>
        <p className="text-lg leading-relaxed mb-6">
          The creator economy has reached travel. Influencers, writers, and photographers are no
          longer just sharing content — they are selling itineraries, hosting trips, and building
          loyal communities around their expertise.
        </p>
        <h2 className="text-2xl font-bold mt-10 mb-4">Premium Guides</h2>
        <p className="leading-relaxed mb-6">
          Instead of relying solely on sponsorships, creators can package their knowledge into
          downloadable guides. A Tokyo food expert can sell a curated ramen and izakaya itinerary to
          thousands of travelers.
        </p>
        <h2 className="text-2xl font-bold mt-10 mb-4">Group Adventures</h2>
        <p className="leading-relaxed">
          Hosting small-group trips lets creators deepen relationships with their audience while
          delivering memorable, high-value experiences. Talery provides the tools to organize,
          communicate, and monetize these adventures.
        </p>
      </>
    ),
  },
};

export async function generateStaticParams() {
  return Object.keys(posts).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: BlogPostPageProps): Promise<Metadata> {
  const { slug } = await params;
  const post = posts[slug];
  if (!post) return { title: "Post Not Found" };
  return {
    title: post.title,
    description: post.excerpt || `Read ${post.title} on the Talery blog.`,
  };
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { slug } = await params;
  const post = posts[slug];

  if (!post) {
    return (
      <main className="min-h-screen">
        <Container className="py-40 text-center">
          <h1 className="text-3xl font-bold mb-4">Post not found</h1>
          <Button asChild variant="outline">
            <Link href="/blog">
              <ArrowLeft className="h-4 w-4 mr-2" /> Back to blog
            </Link>
          </Button>
        </Container>
      </main>
    );
  }

  return (
    <main className="min-h-screen">
      <article>
        <div
          className={`relative pt-36 pb-20 md:pt-44 md:pb-28 bg-gradient-to-br ${post.gradient} text-white`}
        >
          <Container className="relative z-10">
            <ScrollReveal>
              <Button variant="secondary" size="sm" asChild className="mb-6">
                <Link href="/blog">
                  <ArrowLeft className="h-4 w-4 mr-2" /> Back to blog
                </Link>
              </Button>
              <Badge className="mb-4 bg-white/20 text-white border-0">{post.category}</Badge>
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight max-w-4xl mb-6">
                {post.title}
              </h1>
              <div className="flex flex-wrap items-center gap-6 text-sm opacity-90">
                <span className="flex items-center gap-2">
                  <User className="h-4 w-4" /> {post.author}
                </span>
                <span className="flex items-center gap-2">
                  <Calendar className="h-4 w-4" /> {post.date}
                </span>
                <span className="flex items-center gap-2">
                  <Clock className="h-4 w-4" /> {post.readTime}
                </span>
              </div>
            </ScrollReveal>
          </Container>
        </div>

        <Container className="relative z-10 -mt-12">
          <ScrollReveal>
            <div className="max-w-3xl mx-auto bg-card rounded-3xl shadow-xl p-8 md:p-12 border border-border">
              {post.content}
            </div>
          </ScrollReveal>
        </Container>
      </article>
    </main>
  );
}
